"""Comment posted date

Revision ID: 590806225712
Revises: c318b49ab4b0
Create Date: 2019-10-22 11:41:20.588863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '590806225712'
down_revision = 'c318b49ab4b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'posted')
    # ### end Alembic commands ###
