"""Comment model and pitch schema change

Revision ID: 650246285cb3
Revises: 47e84544275e
Create Date: 2019-10-21 09:03:54.239784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650246285cb3'
down_revision = '47e84544275e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pitch_comment', sa.String(), nullable=True),
    sa.Column('pitch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pitches', sa.Column('downvote', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('upvote', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'upvote')
    op.drop_column('pitches', 'downvote')
    op.drop_table('comment')
    # ### end Alembic commands ###
